version: '3.4'

services:
  chatappapi:
    image: chatappapi
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
  chatappweb:
    image: chatappweb
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
